
spool 1_crdb.log append

-- todo:
--  replace hardcoded SID ..

SET VERIFY 	OFF
set feedback  	on
set echo 	on

connect "SYS"/"&&sysPassword" as SYSDBA

set echo off
prompt .
prompt First Start, only works if init-file is present
prompt .

set timing on
set echo on

startup nomount 

CREATE DATABASE "C1"
  MAXINSTANCES 8
  MAXLOGHISTORY 1
  MAXLOGFILES 16
  MAXLOGMEMBERS 3
  MAXDATAFILES 1024
       DATAFILE SIZE 801M AUTOEXTEND ON NEXT 100M  MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL
SYSAUX DATAFILE SIZE 602M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED 
  SMALLFILE DEFAULT TEMPORARY TABLESPACE TEMP 
       TEMPFILE SIZE 103M AUTOEXTEND ON NEXT  50M MAXSIZE UNLIMITED
  SMALLFILE UNDO TABLESPACE "UNDOTBS1" 
       DATAFILE SIZE 204M AUTOEXTEND ON NEXT  50M MAXSIZE UNLIMITED
  CHARACTER SET AL32UTF8
  NATIONAL CHARACTER SET AL16UTF16
  SET DEFAULT BIGFILE TABLESPACE 
LOGFILE 
  GROUP 1  SIZE 200M,
  GROUP 2  SIZE 200M,
  GROUP 3  SIZE 200M
USER SYS IDENTIFIED BY "&&sysPassword" 
USER SYSTEM IDENTIFIED BY "&&systemPassword"
enable pluggable database 
LOCAL UNDO ON
;

CREATE DATABASE "C1"
MAXINSTANCES 8
MAXLOGHISTORY 1
MAXLOGFILES 16
MAXLOGMEMBERS 3
MAXDATAFILES 1024
DATAFILE SIZE 700M AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SYSAUX DATAFILE SIZE 550M AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
SMALLFILE DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE SIZE 20M AUTOEXTEND ON NEXT  640K MAXSIZE UNLIMITED
SMALLFILE UNDO TABLESPACE "UNDOTBS1" DATAFILE  SIZE 200M AUTOEXTEND ON NEXT  5120K MAXSIZE UNLIMITED
CHARACTER SET AL32UTF8
NATIONAL CHARACTER SET AL16UTF16
SET DEFAULT BIGFILE TABLESPACE
LOGFILE GROUP 1  SIZE 200M,
GROUP 2  SIZE 200M,
GROUP 3  SIZE 200M
USER SYS IDENTIFIED BY "&&sysPassword" USER SYSTEM IDENTIFIED BY "&&systemPassword"
enable pluggable database LOCAL UNDO ON;


CREATE DATABASE C1
EXTENT MANAGEMENT LOCAL
DEFAULT TABLESPACE users
DEFAULT TEMPORARY TABLESPACE temp
UNDO TABLESPACE undotbs1
  CHARACTER SET AL32UTF8
ENABLE PLUGGABLE DATABASE
   SEED
   SYSTEM DATAFILES SIZE 40M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
   SYSAUX DATAFILES SIZE 40M;

--enable pluggable database 

set linesize 2048;

column ctl_files NEW_VALUE ctl_files;

select concat('control_files=''', concat(replace(value, ', ', ''','''), '''')) ctl_files from v$parameter where name ='control_files';

set echo on
host echo &ctl_files >>/opt/oracle/admin/c2/scripts/init.ora;

-- check files..
@chk_crdb1

set echo off

prompt .
prompt End of 1_crdb.sql
prompt .

spool off
